version: '3'
services:
  web:                     # <-- service name
    image: nginx:alpine    # use lightweight image
    container_name: cont1
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:Z

