all:
  children:

    production:
      hosts:
        server1:
        server2:

    dr:
      hosts:
        server3:
        server4:

    development:
      hosts:
        dev_server:
          ansible_host: 5.89.1.1

    testing:
      hosts:
        servera.com:
        serverb.com:
        serverc.com:

    webservers:
      hosts:
        server1:
        server2:

    database_servers:
      hosts:
        server2:
        server4:

    marrakech:
      hosts:
        server1:
        server2:
        dev_server:

    casablanca:
      hosts:
        server3:
        server4:

    rabat:
      hosts:
        servera.com:
        serverb.com:
        serverc.com:

  hosts:
    backup_host:
      ansible_host: 50.6.51.123

